# Generated by Django 3.2.4 on 2021-06-22 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('kakao_id', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=13)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
