# Generated by Django 3.2.4 on 2021-06-24 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_auto_20210623_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='dong_code',
            field=models.CharField(default='1', max_length=45),
            preserve_default=False,
        ),
    ]
