# Generated by Django 3.2.4 on 2021-06-30 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_auto_20210630_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='location',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rooms.location'),
        ),
    ]
