# Generated by Django 3.2.4 on 2021-07-17 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0007_alter_room_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.DecimalField(decimal_places=14, max_digits=17, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.DecimalField(decimal_places=14, max_digits=17, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='utmk_x',
            field=models.DecimalField(decimal_places=10, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='utmk_y',
            field=models.DecimalField(decimal_places=10, max_digits=18, null=True),
        ),
    ]
